TK_OVERRIDES = {
    "Thiên Mã Hành Không": r"MDX\ThienMaHanhKhong.mdx",
    "Tọa Vọng Vô Ngã": r"MDX\ToaVongVoNga.mdx",
    "Nhân Kiếm Hợp Nhất": r"MDX\NhanKiemHopNhat.mdx",
    "Mê Tung Huyễn Ảnh": r"MDX\MeTungHuyenAnh.mdx",
    "Mục Dã Lưu Tinh": r"MDX\MucDaLuuTinh.mdx",
    "Tâm Nhãn": r"MDX\TamNhan.mdx",
    "Hỗn Nguyên Nhất Khí": r"MDX\HonNguyenNhatKhi.mdx",
    "Hỏa Liên Phần Hoa": r"MDX\HoaLienPhanHoa.mdx",
    "Nhiếp Hồn Loạn Tâm": r"MDX\NhiepHonLoanTam.mdx",
    "Thiên Ngoại Lưu Tinh": r"MDX\ThienNgoaiLuuTinh.mdx",
    "Hàng Long Hữu Hối": r"MDX\KhangLongHuuHoi.mdx",
    "Hóa Hiểm Vi Di": r"MDX\HoaHiemViDi.mdx",
    "Thời Thừa Lục Long": r"MDX\ThoiThuaLucLong.mdx",
    "Tiềm Long Tại Uyên": r"MDX\TiemLong.mdx",
    "Trảo Long Công": r"MDX\TraoLongCong.mdx",
    "Giáng Long Chưởng": r"MDX\GiangLong.mdx",
    "Cuồng Lôi Chấn Địa": r"MDX\CuongLoi.mdx",
    "Truy Tinh Trục Nguyệt": r"MDX\TruyTinhTrucNguyet.mdx",
    "Âm Phong Thực Cốt": r"MDX\AmPhongThucCot.mdx",
    "Bạo Vũ Lê Hoa": r"MDX\BaoVuLeHoa.mdx",
    "Thất Tuyệt Sát Quang": r"MDX\ThatTuyetSatQuang.mdx",
    "Bất Diệt Bất Tuyệt": r"MDX\BatDietBatTuyet.mdx",
    "Phật Quang Chiến Khí": r"MDX\PhatQuangChienKhi.mdx",
    "Liệt Hỏa Tinh Thiên": r"MDX\LietHoaTinhThien.mdx",
    "Vân Long Kích": r"MDX\VanLong.mdx",
    "Vân Long Tam Hiện": r"MDX\VanLong.mdx",
    "Bác Cập Nhị Phục": r"MDX\BacCapNhiPhuc.mdx",
    "Bát Quái Du Long": r"MDX\BatQuaiDuLong.mdx",
    "Thái Cực Thần Công": r"MDX\ThaiCucThanCong.mdx",
    "Ngạo Tuyết Tiếu Phong": r"MDX\NgaoTuyetTieuPhong.mdx",
    "Vô Nhân Vô Ngã": r"MDX\VoNhanVoNga.mdx",
    "Túy Tiên Bát Côn": r"MDX\TuyTien.mdx",
    "Bắc Minh Thần Công": r"MDX\BacMinhThanCong.mdx",
    "Thừa Long Quyết": r"MDX\ThuaLongQuyet.mdx",
    "Minh Sát Thu Hào": r"MDX\MinhSatThuHao.mdx",
    "Thiên Phật Thiên Diệp": r"MDX\ThienPhat.mdx",
    "Thánh Hỏa Phần Tâm": r"MDX\ThanhHoaPhanTam.mdx",
    "Vạn Vật Câu Phần": r"MDX\VanVat.mdx",
    "Thánh Hỏa Liêu Nguyên": r"MDX\ThanhHoa.mdx",
    "Thánh Hỏa Lệnh Pháp": r"MDX\ThanhHoa.mdx",
    "Thánh Hỏa Thần Công": r"MDX\ThanhHoa.mdx",
    "Thần Chỉ Điểm Huyệt": r"MDX\ThanChi.mdx",
    "Nhất Dương Chỉ": r"MDX\NhatDuongChi.mdx",
    "Cản Dương Thần Chỉ": r"MDX\CanDuong.mdx",
    "Thiên Long Thần Chỉ": r"MDX\ThanChi.mdx",
    "Cô Thân Chi Ảnh": r"MDX\ThanChi.mdx",
    "Dương Ca Thiên Quân": r"MDX\Cat.mdx",
    "Phong Quyển Tàn Tuyết": r"MDX\PhongQuyen.mdx",
    "Băng Tâm Tiên Tử": r"MDX\BangTamTienTu.mdx",
}
